// Code generated by ent, DO NOT EDIT.

package bindkeygiftsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the bindkeygiftsetting type in the database.
	Label = "bind_key_gift_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldDeductionMode holds the string denoting the deduction_mode field in the database.
	FieldDeductionMode = "deduction_mode"
	// FieldRatioRecharge holds the string denoting the ratio_recharge field in the database.
	FieldRatioRecharge = "ratio_recharge"
	// FieldExpiresAfterDays holds the string denoting the expires_after_days field in the database.
	FieldExpiresAfterDays = "expires_after_days"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// Table holds the table name of the bindkeygiftsetting in the database.
	Table = "bind_key_gift_settings"
)

// Columns holds all SQL columns for bindkeygiftsetting fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAPIKeyID,
	FieldDeductionMode,
	FieldRatioRecharge,
	FieldExpiresAfterDays,
	FieldConfig,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DeductionModeValidator is a validator for the "deduction_mode" field. It is called by the builders before save.
	DeductionModeValidator func(string) error
)

// OrderOption defines the ordering options for the BindKeyGiftSetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByDeductionMode orders the results by the deduction_mode field.
func ByDeductionMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeductionMode, opts...).ToFunc()
}

// ByRatioRecharge orders the results by the ratio_recharge field.
func ByRatioRecharge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRatioRecharge, opts...).ToFunc()
}

// ByExpiresAfterDays orders the results by the expires_after_days field.
func ByExpiresAfterDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAfterDays, opts...).ToFunc()
}
