// Code generated by ent, DO NOT EDIT.

package bindkeygiftsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldAPIKeyID, v))
}

// DeductionMode applies equality check predicate on the "deduction_mode" field. It's identical to DeductionModeEQ.
func DeductionMode(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldDeductionMode, v))
}

// RatioRecharge applies equality check predicate on the "ratio_recharge" field. It's identical to RatioRechargeEQ.
func RatioRecharge(v float64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldRatioRecharge, v))
}

// ExpiresAfterDays applies equality check predicate on the "expires_after_days" field. It's identical to ExpiresAfterDaysEQ.
func ExpiresAfterDays(v int) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldExpiresAfterDays, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLTE(FieldAPIKeyID, v))
}

// DeductionModeEQ applies the EQ predicate on the "deduction_mode" field.
func DeductionModeEQ(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldDeductionMode, v))
}

// DeductionModeNEQ applies the NEQ predicate on the "deduction_mode" field.
func DeductionModeNEQ(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNEQ(FieldDeductionMode, v))
}

// DeductionModeIn applies the In predicate on the "deduction_mode" field.
func DeductionModeIn(vs ...string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldIn(FieldDeductionMode, vs...))
}

// DeductionModeNotIn applies the NotIn predicate on the "deduction_mode" field.
func DeductionModeNotIn(vs ...string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNotIn(FieldDeductionMode, vs...))
}

// DeductionModeGT applies the GT predicate on the "deduction_mode" field.
func DeductionModeGT(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGT(FieldDeductionMode, v))
}

// DeductionModeGTE applies the GTE predicate on the "deduction_mode" field.
func DeductionModeGTE(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGTE(FieldDeductionMode, v))
}

// DeductionModeLT applies the LT predicate on the "deduction_mode" field.
func DeductionModeLT(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLT(FieldDeductionMode, v))
}

// DeductionModeLTE applies the LTE predicate on the "deduction_mode" field.
func DeductionModeLTE(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLTE(FieldDeductionMode, v))
}

// DeductionModeContains applies the Contains predicate on the "deduction_mode" field.
func DeductionModeContains(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldContains(FieldDeductionMode, v))
}

// DeductionModeHasPrefix applies the HasPrefix predicate on the "deduction_mode" field.
func DeductionModeHasPrefix(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldHasPrefix(FieldDeductionMode, v))
}

// DeductionModeHasSuffix applies the HasSuffix predicate on the "deduction_mode" field.
func DeductionModeHasSuffix(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldHasSuffix(FieldDeductionMode, v))
}

// DeductionModeEqualFold applies the EqualFold predicate on the "deduction_mode" field.
func DeductionModeEqualFold(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEqualFold(FieldDeductionMode, v))
}

// DeductionModeContainsFold applies the ContainsFold predicate on the "deduction_mode" field.
func DeductionModeContainsFold(v string) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldContainsFold(FieldDeductionMode, v))
}

// RatioRechargeEQ applies the EQ predicate on the "ratio_recharge" field.
func RatioRechargeEQ(v float64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldRatioRecharge, v))
}

// RatioRechargeNEQ applies the NEQ predicate on the "ratio_recharge" field.
func RatioRechargeNEQ(v float64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNEQ(FieldRatioRecharge, v))
}

// RatioRechargeIn applies the In predicate on the "ratio_recharge" field.
func RatioRechargeIn(vs ...float64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldIn(FieldRatioRecharge, vs...))
}

// RatioRechargeNotIn applies the NotIn predicate on the "ratio_recharge" field.
func RatioRechargeNotIn(vs ...float64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNotIn(FieldRatioRecharge, vs...))
}

// RatioRechargeGT applies the GT predicate on the "ratio_recharge" field.
func RatioRechargeGT(v float64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGT(FieldRatioRecharge, v))
}

// RatioRechargeGTE applies the GTE predicate on the "ratio_recharge" field.
func RatioRechargeGTE(v float64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGTE(FieldRatioRecharge, v))
}

// RatioRechargeLT applies the LT predicate on the "ratio_recharge" field.
func RatioRechargeLT(v float64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLT(FieldRatioRecharge, v))
}

// RatioRechargeLTE applies the LTE predicate on the "ratio_recharge" field.
func RatioRechargeLTE(v float64) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLTE(FieldRatioRecharge, v))
}

// RatioRechargeIsNil applies the IsNil predicate on the "ratio_recharge" field.
func RatioRechargeIsNil() predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldIsNull(FieldRatioRecharge))
}

// RatioRechargeNotNil applies the NotNil predicate on the "ratio_recharge" field.
func RatioRechargeNotNil() predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNotNull(FieldRatioRecharge))
}

// ExpiresAfterDaysEQ applies the EQ predicate on the "expires_after_days" field.
func ExpiresAfterDaysEQ(v int) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldEQ(FieldExpiresAfterDays, v))
}

// ExpiresAfterDaysNEQ applies the NEQ predicate on the "expires_after_days" field.
func ExpiresAfterDaysNEQ(v int) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNEQ(FieldExpiresAfterDays, v))
}

// ExpiresAfterDaysIn applies the In predicate on the "expires_after_days" field.
func ExpiresAfterDaysIn(vs ...int) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldIn(FieldExpiresAfterDays, vs...))
}

// ExpiresAfterDaysNotIn applies the NotIn predicate on the "expires_after_days" field.
func ExpiresAfterDaysNotIn(vs ...int) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNotIn(FieldExpiresAfterDays, vs...))
}

// ExpiresAfterDaysGT applies the GT predicate on the "expires_after_days" field.
func ExpiresAfterDaysGT(v int) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGT(FieldExpiresAfterDays, v))
}

// ExpiresAfterDaysGTE applies the GTE predicate on the "expires_after_days" field.
func ExpiresAfterDaysGTE(v int) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldGTE(FieldExpiresAfterDays, v))
}

// ExpiresAfterDaysLT applies the LT predicate on the "expires_after_days" field.
func ExpiresAfterDaysLT(v int) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLT(FieldExpiresAfterDays, v))
}

// ExpiresAfterDaysLTE applies the LTE predicate on the "expires_after_days" field.
func ExpiresAfterDaysLTE(v int) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldLTE(FieldExpiresAfterDays, v))
}

// ExpiresAfterDaysIsNil applies the IsNil predicate on the "expires_after_days" field.
func ExpiresAfterDaysIsNil() predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldIsNull(FieldExpiresAfterDays))
}

// ExpiresAfterDaysNotNil applies the NotNil predicate on the "expires_after_days" field.
func ExpiresAfterDaysNotNil() predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.FieldNotNull(FieldExpiresAfterDays))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BindKeyGiftSetting) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BindKeyGiftSetting) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BindKeyGiftSetting) predicate.BindKeyGiftSetting {
	return predicate.BindKeyGiftSetting(sql.NotPredicates(p))
}
