// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/bindkeygiftsetting"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// BindKeyGiftSetting is the model entity for the BindKeyGiftSetting schema.
type BindKeyGiftSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// DeductionMode holds the value of the "deduction_mode" field.
	DeductionMode string `json:"deduction_mode,omitempty"`
	// RatioRecharge holds the value of the "ratio_recharge" field.
	RatioRecharge *float64 `json:"ratio_recharge,omitempty"`
	// ExpiresAfterDays holds the value of the "expires_after_days" field.
	ExpiresAfterDays *int `json:"expires_after_days,omitempty"`
	// ActivityID holds the value of the "activity_id" field.
	ActivityID *int64 `json:"activity_id,omitempty"`
	// Config holds the value of the "config" field.
	Config       *domain.BindKeyConfig `json:"config,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BindKeyGiftSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bindkeygiftsetting.FieldConfig:
			values[i] = new([]byte)
		case bindkeygiftsetting.FieldRatioRecharge:
			values[i] = new(sql.NullFloat64)
		case bindkeygiftsetting.FieldID, bindkeygiftsetting.FieldAPIKeyID, bindkeygiftsetting.FieldExpiresAfterDays, bindkeygiftsetting.FieldActivityID:
			values[i] = new(sql.NullInt64)
		case bindkeygiftsetting.FieldDeductionMode:
			values[i] = new(sql.NullString)
		case bindkeygiftsetting.FieldCreatedAt, bindkeygiftsetting.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BindKeyGiftSetting fields.
func (_m *BindKeyGiftSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bindkeygiftsetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case bindkeygiftsetting.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case bindkeygiftsetting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case bindkeygiftsetting.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case bindkeygiftsetting.FieldDeductionMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deduction_mode", values[i])
			} else if value.Valid {
				_m.DeductionMode = value.String
			}
		case bindkeygiftsetting.FieldRatioRecharge:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field ratio_recharge", values[i])
			} else if value.Valid {
				_m.RatioRecharge = new(float64)
				*_m.RatioRecharge = value.Float64
			}
		case bindkeygiftsetting.FieldExpiresAfterDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expires_after_days", values[i])
			} else if value.Valid {
				_m.ExpiresAfterDays = new(int)
				*_m.ExpiresAfterDays = int(value.Int64)
			}
		case bindkeygiftsetting.FieldActivityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field activity_id", values[i])
			} else if value.Valid {
				_m.ActivityID = new(int64)
				*_m.ActivityID = value.Int64
			}
		case bindkeygiftsetting.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BindKeyGiftSetting.
// This includes values selected through modifiers, order, etc.
func (_m *BindKeyGiftSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BindKeyGiftSetting.
// Note that you need to call BindKeyGiftSetting.Unwrap() before calling this method if this BindKeyGiftSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BindKeyGiftSetting) Update() *BindKeyGiftSettingUpdateOne {
	return NewBindKeyGiftSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BindKeyGiftSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BindKeyGiftSetting) Unwrap() *BindKeyGiftSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BindKeyGiftSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BindKeyGiftSetting) String() string {
	var builder strings.Builder
	builder.WriteString("BindKeyGiftSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("deduction_mode=")
	builder.WriteString(_m.DeductionMode)
	builder.WriteString(", ")
	if v := _m.RatioRecharge; v != nil {
		builder.WriteString("ratio_recharge=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAfterDays; v != nil {
		builder.WriteString("expires_after_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActivityID; v != nil {
		builder.WriteString("activity_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", _m.Config))
	builder.WriteByte(')')
	return builder.String()
}

// BindKeyGiftSettings is a parsable slice of BindKeyGiftSetting.
type BindKeyGiftSettings []*BindKeyGiftSetting
