// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bindkeygiftsetting"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BindKeyGiftSettingDelete is the builder for deleting a BindKeyGiftSetting entity.
type BindKeyGiftSettingDelete struct {
	config
	hooks    []Hook
	mutation *BindKeyGiftSettingMutation
}

// Where appends a list predicates to the BindKeyGiftSettingDelete builder.
func (_d *BindKeyGiftSettingDelete) Where(ps ...predicate.BindKeyGiftSetting) *BindKeyGiftSettingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BindKeyGiftSettingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BindKeyGiftSettingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BindKeyGiftSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bindkeygiftsetting.Table, sqlgraph.NewFieldSpec(bindkeygiftsetting.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BindKeyGiftSettingDeleteOne is the builder for deleting a single BindKeyGiftSetting entity.
type BindKeyGiftSettingDeleteOne struct {
	_d *BindKeyGiftSettingDelete
}

// Where appends a list predicates to the BindKeyGiftSettingDelete builder.
func (_d *BindKeyGiftSettingDeleteOne) Where(ps ...predicate.BindKeyGiftSetting) *BindKeyGiftSettingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BindKeyGiftSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bindkeygiftsetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BindKeyGiftSettingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
