// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bindkeygiftsetting"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// BindKeyGiftSettingUpdate is the builder for updating BindKeyGiftSetting entities.
type BindKeyGiftSettingUpdate struct {
	config
	hooks    []Hook
	mutation *BindKeyGiftSettingMutation
}

// Where appends a list predicates to the BindKeyGiftSettingUpdate builder.
func (_u *BindKeyGiftSettingUpdate) Where(ps ...predicate.BindKeyGiftSetting) *BindKeyGiftSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BindKeyGiftSettingUpdate) SetUpdatedAt(v time.Time) *BindKeyGiftSettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *BindKeyGiftSettingUpdate) SetAPIKeyID(v int64) *BindKeyGiftSettingUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *BindKeyGiftSettingUpdate) SetNillableAPIKeyID(v *int64) *BindKeyGiftSettingUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *BindKeyGiftSettingUpdate) AddAPIKeyID(v int64) *BindKeyGiftSettingUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetDeductionMode sets the "deduction_mode" field.
func (_u *BindKeyGiftSettingUpdate) SetDeductionMode(v string) *BindKeyGiftSettingUpdate {
	_u.mutation.SetDeductionMode(v)
	return _u
}

// SetNillableDeductionMode sets the "deduction_mode" field if the given value is not nil.
func (_u *BindKeyGiftSettingUpdate) SetNillableDeductionMode(v *string) *BindKeyGiftSettingUpdate {
	if v != nil {
		_u.SetDeductionMode(*v)
	}
	return _u
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (_u *BindKeyGiftSettingUpdate) SetRatioRecharge(v float64) *BindKeyGiftSettingUpdate {
	_u.mutation.ResetRatioRecharge()
	_u.mutation.SetRatioRecharge(v)
	return _u
}

// SetNillableRatioRecharge sets the "ratio_recharge" field if the given value is not nil.
func (_u *BindKeyGiftSettingUpdate) SetNillableRatioRecharge(v *float64) *BindKeyGiftSettingUpdate {
	if v != nil {
		_u.SetRatioRecharge(*v)
	}
	return _u
}

// AddRatioRecharge adds value to the "ratio_recharge" field.
func (_u *BindKeyGiftSettingUpdate) AddRatioRecharge(v float64) *BindKeyGiftSettingUpdate {
	_u.mutation.AddRatioRecharge(v)
	return _u
}

// ClearRatioRecharge clears the value of the "ratio_recharge" field.
func (_u *BindKeyGiftSettingUpdate) ClearRatioRecharge() *BindKeyGiftSettingUpdate {
	_u.mutation.ClearRatioRecharge()
	return _u
}

// SetExpiresAfterDays sets the "expires_after_days" field.
func (_u *BindKeyGiftSettingUpdate) SetExpiresAfterDays(v int) *BindKeyGiftSettingUpdate {
	_u.mutation.ResetExpiresAfterDays()
	_u.mutation.SetExpiresAfterDays(v)
	return _u
}

// SetNillableExpiresAfterDays sets the "expires_after_days" field if the given value is not nil.
func (_u *BindKeyGiftSettingUpdate) SetNillableExpiresAfterDays(v *int) *BindKeyGiftSettingUpdate {
	if v != nil {
		_u.SetExpiresAfterDays(*v)
	}
	return _u
}

// AddExpiresAfterDays adds value to the "expires_after_days" field.
func (_u *BindKeyGiftSettingUpdate) AddExpiresAfterDays(v int) *BindKeyGiftSettingUpdate {
	_u.mutation.AddExpiresAfterDays(v)
	return _u
}

// ClearExpiresAfterDays clears the value of the "expires_after_days" field.
func (_u *BindKeyGiftSettingUpdate) ClearExpiresAfterDays() *BindKeyGiftSettingUpdate {
	_u.mutation.ClearExpiresAfterDays()
	return _u
}

// SetConfig sets the "config" field.
func (_u *BindKeyGiftSettingUpdate) SetConfig(v *domain.BindKeyConfig) *BindKeyGiftSettingUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *BindKeyGiftSettingUpdate) ClearConfig() *BindKeyGiftSettingUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// Mutation returns the BindKeyGiftSettingMutation object of the builder.
func (_u *BindKeyGiftSettingUpdate) Mutation() *BindKeyGiftSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BindKeyGiftSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BindKeyGiftSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BindKeyGiftSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BindKeyGiftSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BindKeyGiftSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bindkeygiftsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BindKeyGiftSettingUpdate) check() error {
	if v, ok := _u.mutation.DeductionMode(); ok {
		if err := bindkeygiftsetting.DeductionModeValidator(v); err != nil {
			return &ValidationError{Name: "deduction_mode", err: fmt.Errorf(`ent: validator failed for field "BindKeyGiftSetting.deduction_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *BindKeyGiftSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bindkeygiftsetting.Table, bindkeygiftsetting.Columns, sqlgraph.NewFieldSpec(bindkeygiftsetting.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bindkeygiftsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(bindkeygiftsetting.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(bindkeygiftsetting.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeductionMode(); ok {
		_spec.SetField(bindkeygiftsetting.FieldDeductionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RatioRecharge(); ok {
		_spec.SetField(bindkeygiftsetting.FieldRatioRecharge, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRatioRecharge(); ok {
		_spec.AddField(bindkeygiftsetting.FieldRatioRecharge, field.TypeFloat64, value)
	}
	if _u.mutation.RatioRechargeCleared() {
		_spec.ClearField(bindkeygiftsetting.FieldRatioRecharge, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExpiresAfterDays(); ok {
		_spec.SetField(bindkeygiftsetting.FieldExpiresAfterDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpiresAfterDays(); ok {
		_spec.AddField(bindkeygiftsetting.FieldExpiresAfterDays, field.TypeInt, value)
	}
	if _u.mutation.ExpiresAfterDaysCleared() {
		_spec.ClearField(bindkeygiftsetting.FieldExpiresAfterDays, field.TypeInt)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(bindkeygiftsetting.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(bindkeygiftsetting.FieldConfig, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bindkeygiftsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BindKeyGiftSettingUpdateOne is the builder for updating a single BindKeyGiftSetting entity.
type BindKeyGiftSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BindKeyGiftSettingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BindKeyGiftSettingUpdateOne) SetUpdatedAt(v time.Time) *BindKeyGiftSettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *BindKeyGiftSettingUpdateOne) SetAPIKeyID(v int64) *BindKeyGiftSettingUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *BindKeyGiftSettingUpdateOne) SetNillableAPIKeyID(v *int64) *BindKeyGiftSettingUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *BindKeyGiftSettingUpdateOne) AddAPIKeyID(v int64) *BindKeyGiftSettingUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetDeductionMode sets the "deduction_mode" field.
func (_u *BindKeyGiftSettingUpdateOne) SetDeductionMode(v string) *BindKeyGiftSettingUpdateOne {
	_u.mutation.SetDeductionMode(v)
	return _u
}

// SetNillableDeductionMode sets the "deduction_mode" field if the given value is not nil.
func (_u *BindKeyGiftSettingUpdateOne) SetNillableDeductionMode(v *string) *BindKeyGiftSettingUpdateOne {
	if v != nil {
		_u.SetDeductionMode(*v)
	}
	return _u
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (_u *BindKeyGiftSettingUpdateOne) SetRatioRecharge(v float64) *BindKeyGiftSettingUpdateOne {
	_u.mutation.ResetRatioRecharge()
	_u.mutation.SetRatioRecharge(v)
	return _u
}

// SetNillableRatioRecharge sets the "ratio_recharge" field if the given value is not nil.
func (_u *BindKeyGiftSettingUpdateOne) SetNillableRatioRecharge(v *float64) *BindKeyGiftSettingUpdateOne {
	if v != nil {
		_u.SetRatioRecharge(*v)
	}
	return _u
}

// AddRatioRecharge adds value to the "ratio_recharge" field.
func (_u *BindKeyGiftSettingUpdateOne) AddRatioRecharge(v float64) *BindKeyGiftSettingUpdateOne {
	_u.mutation.AddRatioRecharge(v)
	return _u
}

// ClearRatioRecharge clears the value of the "ratio_recharge" field.
func (_u *BindKeyGiftSettingUpdateOne) ClearRatioRecharge() *BindKeyGiftSettingUpdateOne {
	_u.mutation.ClearRatioRecharge()
	return _u
}

// SetExpiresAfterDays sets the "expires_after_days" field.
func (_u *BindKeyGiftSettingUpdateOne) SetExpiresAfterDays(v int) *BindKeyGiftSettingUpdateOne {
	_u.mutation.ResetExpiresAfterDays()
	_u.mutation.SetExpiresAfterDays(v)
	return _u
}

// SetNillableExpiresAfterDays sets the "expires_after_days" field if the given value is not nil.
func (_u *BindKeyGiftSettingUpdateOne) SetNillableExpiresAfterDays(v *int) *BindKeyGiftSettingUpdateOne {
	if v != nil {
		_u.SetExpiresAfterDays(*v)
	}
	return _u
}

// AddExpiresAfterDays adds value to the "expires_after_days" field.
func (_u *BindKeyGiftSettingUpdateOne) AddExpiresAfterDays(v int) *BindKeyGiftSettingUpdateOne {
	_u.mutation.AddExpiresAfterDays(v)
	return _u
}

// ClearExpiresAfterDays clears the value of the "expires_after_days" field.
func (_u *BindKeyGiftSettingUpdateOne) ClearExpiresAfterDays() *BindKeyGiftSettingUpdateOne {
	_u.mutation.ClearExpiresAfterDays()
	return _u
}

// SetConfig sets the "config" field.
func (_u *BindKeyGiftSettingUpdateOne) SetConfig(v *domain.BindKeyConfig) *BindKeyGiftSettingUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *BindKeyGiftSettingUpdateOne) ClearConfig() *BindKeyGiftSettingUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// Mutation returns the BindKeyGiftSettingMutation object of the builder.
func (_u *BindKeyGiftSettingUpdateOne) Mutation() *BindKeyGiftSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the BindKeyGiftSettingUpdate builder.
func (_u *BindKeyGiftSettingUpdateOne) Where(ps ...predicate.BindKeyGiftSetting) *BindKeyGiftSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BindKeyGiftSettingUpdateOne) Select(field string, fields ...string) *BindKeyGiftSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BindKeyGiftSetting entity.
func (_u *BindKeyGiftSettingUpdateOne) Save(ctx context.Context) (*BindKeyGiftSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BindKeyGiftSettingUpdateOne) SaveX(ctx context.Context) *BindKeyGiftSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BindKeyGiftSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BindKeyGiftSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BindKeyGiftSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bindkeygiftsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BindKeyGiftSettingUpdateOne) check() error {
	if v, ok := _u.mutation.DeductionMode(); ok {
		if err := bindkeygiftsetting.DeductionModeValidator(v); err != nil {
			return &ValidationError{Name: "deduction_mode", err: fmt.Errorf(`ent: validator failed for field "BindKeyGiftSetting.deduction_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *BindKeyGiftSettingUpdateOne) sqlSave(ctx context.Context) (_node *BindKeyGiftSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bindkeygiftsetting.Table, bindkeygiftsetting.Columns, sqlgraph.NewFieldSpec(bindkeygiftsetting.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BindKeyGiftSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bindkeygiftsetting.FieldID)
		for _, f := range fields {
			if !bindkeygiftsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bindkeygiftsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bindkeygiftsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(bindkeygiftsetting.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(bindkeygiftsetting.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeductionMode(); ok {
		_spec.SetField(bindkeygiftsetting.FieldDeductionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RatioRecharge(); ok {
		_spec.SetField(bindkeygiftsetting.FieldRatioRecharge, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRatioRecharge(); ok {
		_spec.AddField(bindkeygiftsetting.FieldRatioRecharge, field.TypeFloat64, value)
	}
	if _u.mutation.RatioRechargeCleared() {
		_spec.ClearField(bindkeygiftsetting.FieldRatioRecharge, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExpiresAfterDays(); ok {
		_spec.SetField(bindkeygiftsetting.FieldExpiresAfterDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpiresAfterDays(); ok {
		_spec.AddField(bindkeygiftsetting.FieldExpiresAfterDays, field.TypeInt, value)
	}
	if _u.mutation.ExpiresAfterDaysCleared() {
		_spec.ClearField(bindkeygiftsetting.FieldExpiresAfterDays, field.TypeInt)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(bindkeygiftsetting.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(bindkeygiftsetting.FieldConfig, field.TypeJSON)
	}
	_node = &BindKeyGiftSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bindkeygiftsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
