// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bindkeygiftsetting"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// BindKeyGiftSettingCreate is the builder for creating a BindKeyGiftSetting entity.
type BindKeyGiftSettingCreate struct {
	config
	mutation *BindKeyGiftSettingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BindKeyGiftSettingCreate) SetCreatedAt(v time.Time) *BindKeyGiftSettingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BindKeyGiftSettingCreate) SetNillableCreatedAt(v *time.Time) *BindKeyGiftSettingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BindKeyGiftSettingCreate) SetUpdatedAt(v time.Time) *BindKeyGiftSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BindKeyGiftSettingCreate) SetNillableUpdatedAt(v *time.Time) *BindKeyGiftSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *BindKeyGiftSettingCreate) SetAPIKeyID(v int64) *BindKeyGiftSettingCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetDeductionMode sets the "deduction_mode" field.
func (_c *BindKeyGiftSettingCreate) SetDeductionMode(v string) *BindKeyGiftSettingCreate {
	_c.mutation.SetDeductionMode(v)
	return _c
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (_c *BindKeyGiftSettingCreate) SetRatioRecharge(v float64) *BindKeyGiftSettingCreate {
	_c.mutation.SetRatioRecharge(v)
	return _c
}

// SetNillableRatioRecharge sets the "ratio_recharge" field if the given value is not nil.
func (_c *BindKeyGiftSettingCreate) SetNillableRatioRecharge(v *float64) *BindKeyGiftSettingCreate {
	if v != nil {
		_c.SetRatioRecharge(*v)
	}
	return _c
}

// SetExpiresAfterDays sets the "expires_after_days" field.
func (_c *BindKeyGiftSettingCreate) SetExpiresAfterDays(v int) *BindKeyGiftSettingCreate {
	_c.mutation.SetExpiresAfterDays(v)
	return _c
}

// SetNillableExpiresAfterDays sets the "expires_after_days" field if the given value is not nil.
func (_c *BindKeyGiftSettingCreate) SetNillableExpiresAfterDays(v *int) *BindKeyGiftSettingCreate {
	if v != nil {
		_c.SetExpiresAfterDays(*v)
	}
	return _c
}

// SetActivityID sets the "activity_id" field.
func (_c *BindKeyGiftSettingCreate) SetActivityID(v int64) *BindKeyGiftSettingCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_c *BindKeyGiftSettingCreate) SetNillableActivityID(v *int64) *BindKeyGiftSettingCreate {
	if v != nil {
		_c.SetActivityID(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *BindKeyGiftSettingCreate) SetConfig(v *domain.BindKeyConfig) *BindKeyGiftSettingCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// Mutation returns the BindKeyGiftSettingMutation object of the builder.
func (_c *BindKeyGiftSettingCreate) Mutation() *BindKeyGiftSettingMutation {
	return _c.mutation
}

// Save creates the BindKeyGiftSetting in the database.
func (_c *BindKeyGiftSettingCreate) Save(ctx context.Context) (*BindKeyGiftSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BindKeyGiftSettingCreate) SaveX(ctx context.Context) *BindKeyGiftSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BindKeyGiftSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BindKeyGiftSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BindKeyGiftSettingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := bindkeygiftsetting.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := bindkeygiftsetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BindKeyGiftSettingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BindKeyGiftSetting.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BindKeyGiftSetting.updated_at"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "BindKeyGiftSetting.api_key_id"`)}
	}
	if _, ok := _c.mutation.DeductionMode(); !ok {
		return &ValidationError{Name: "deduction_mode", err: errors.New(`ent: missing required field "BindKeyGiftSetting.deduction_mode"`)}
	}
	if v, ok := _c.mutation.DeductionMode(); ok {
		if err := bindkeygiftsetting.DeductionModeValidator(v); err != nil {
			return &ValidationError{Name: "deduction_mode", err: fmt.Errorf(`ent: validator failed for field "BindKeyGiftSetting.deduction_mode": %w`, err)}
		}
	}
	return nil
}

func (_c *BindKeyGiftSettingCreate) sqlSave(ctx context.Context) (*BindKeyGiftSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BindKeyGiftSettingCreate) createSpec() (*BindKeyGiftSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &BindKeyGiftSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bindkeygiftsetting.Table, sqlgraph.NewFieldSpec(bindkeygiftsetting.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(bindkeygiftsetting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(bindkeygiftsetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(bindkeygiftsetting.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.DeductionMode(); ok {
		_spec.SetField(bindkeygiftsetting.FieldDeductionMode, field.TypeString, value)
		_node.DeductionMode = value
	}
	if value, ok := _c.mutation.RatioRecharge(); ok {
		_spec.SetField(bindkeygiftsetting.FieldRatioRecharge, field.TypeFloat64, value)
		_node.RatioRecharge = &value
	}
	if value, ok := _c.mutation.ExpiresAfterDays(); ok {
		_spec.SetField(bindkeygiftsetting.FieldExpiresAfterDays, field.TypeInt, value)
		_node.ExpiresAfterDays = &value
	}
	if value, ok := _c.mutation.ActivityID(); ok {
		_spec.SetField(bindkeygiftsetting.FieldActivityID, field.TypeInt64, value)
		_node.ActivityID = &value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(bindkeygiftsetting.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BindKeyGiftSetting.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BindKeyGiftSettingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BindKeyGiftSettingCreate) OnConflict(opts ...sql.ConflictOption) *BindKeyGiftSettingUpsertOne {
	_c.conflict = opts
	return &BindKeyGiftSettingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BindKeyGiftSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BindKeyGiftSettingCreate) OnConflictColumns(columns ...string) *BindKeyGiftSettingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BindKeyGiftSettingUpsertOne{
		create: _c,
	}
}

type (
	// BindKeyGiftSettingUpsertOne is the builder for "upsert"-ing
	//  one BindKeyGiftSetting node.
	BindKeyGiftSettingUpsertOne struct {
		create *BindKeyGiftSettingCreate
	}

	// BindKeyGiftSettingUpsert is the "OnConflict" setter.
	BindKeyGiftSettingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BindKeyGiftSettingUpsert) SetUpdatedAt(v time.Time) *BindKeyGiftSettingUpsert {
	u.Set(bindkeygiftsetting.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsert) UpdateUpdatedAt() *BindKeyGiftSettingUpsert {
	u.SetExcluded(bindkeygiftsetting.FieldUpdatedAt)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *BindKeyGiftSettingUpsert) SetAPIKeyID(v int64) *BindKeyGiftSettingUpsert {
	u.Set(bindkeygiftsetting.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsert) UpdateAPIKeyID() *BindKeyGiftSettingUpsert {
	u.SetExcluded(bindkeygiftsetting.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *BindKeyGiftSettingUpsert) AddAPIKeyID(v int64) *BindKeyGiftSettingUpsert {
	u.Add(bindkeygiftsetting.FieldAPIKeyID, v)
	return u
}

// SetDeductionMode sets the "deduction_mode" field.
func (u *BindKeyGiftSettingUpsert) SetDeductionMode(v string) *BindKeyGiftSettingUpsert {
	u.Set(bindkeygiftsetting.FieldDeductionMode, v)
	return u
}

// UpdateDeductionMode sets the "deduction_mode" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsert) UpdateDeductionMode() *BindKeyGiftSettingUpsert {
	u.SetExcluded(bindkeygiftsetting.FieldDeductionMode)
	return u
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (u *BindKeyGiftSettingUpsert) SetRatioRecharge(v float64) *BindKeyGiftSettingUpsert {
	u.Set(bindkeygiftsetting.FieldRatioRecharge, v)
	return u
}

// UpdateRatioRecharge sets the "ratio_recharge" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsert) UpdateRatioRecharge() *BindKeyGiftSettingUpsert {
	u.SetExcluded(bindkeygiftsetting.FieldRatioRecharge)
	return u
}

// AddRatioRecharge adds v to the "ratio_recharge" field.
func (u *BindKeyGiftSettingUpsert) AddRatioRecharge(v float64) *BindKeyGiftSettingUpsert {
	u.Add(bindkeygiftsetting.FieldRatioRecharge, v)
	return u
}

// ClearRatioRecharge clears the value of the "ratio_recharge" field.
func (u *BindKeyGiftSettingUpsert) ClearRatioRecharge() *BindKeyGiftSettingUpsert {
	u.SetNull(bindkeygiftsetting.FieldRatioRecharge)
	return u
}

// SetExpiresAfterDays sets the "expires_after_days" field.
func (u *BindKeyGiftSettingUpsert) SetExpiresAfterDays(v int) *BindKeyGiftSettingUpsert {
	u.Set(bindkeygiftsetting.FieldExpiresAfterDays, v)
	return u
}

// UpdateExpiresAfterDays sets the "expires_after_days" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsert) UpdateExpiresAfterDays() *BindKeyGiftSettingUpsert {
	u.SetExcluded(bindkeygiftsetting.FieldExpiresAfterDays)
	return u
}

// AddExpiresAfterDays adds v to the "expires_after_days" field.
func (u *BindKeyGiftSettingUpsert) AddExpiresAfterDays(v int) *BindKeyGiftSettingUpsert {
	u.Add(bindkeygiftsetting.FieldExpiresAfterDays, v)
	return u
}

// ClearExpiresAfterDays clears the value of the "expires_after_days" field.
func (u *BindKeyGiftSettingUpsert) ClearExpiresAfterDays() *BindKeyGiftSettingUpsert {
	u.SetNull(bindkeygiftsetting.FieldExpiresAfterDays)
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *BindKeyGiftSettingUpsert) SetActivityID(v int64) *BindKeyGiftSettingUpsert {
	u.Set(bindkeygiftsetting.FieldActivityID, v)
	return u
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsert) UpdateActivityID() *BindKeyGiftSettingUpsert {
	u.SetExcluded(bindkeygiftsetting.FieldActivityID)
	return u
}

// AddActivityID adds v to the "activity_id" field.
func (u *BindKeyGiftSettingUpsert) AddActivityID(v int64) *BindKeyGiftSettingUpsert {
	u.Add(bindkeygiftsetting.FieldActivityID, v)
	return u
}

// ClearActivityID clears the value of the "activity_id" field.
func (u *BindKeyGiftSettingUpsert) ClearActivityID() *BindKeyGiftSettingUpsert {
	u.SetNull(bindkeygiftsetting.FieldActivityID)
	return u
}

// SetConfig sets the "config" field.
func (u *BindKeyGiftSettingUpsert) SetConfig(v *domain.BindKeyConfig) *BindKeyGiftSettingUpsert {
	u.Set(bindkeygiftsetting.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsert) UpdateConfig() *BindKeyGiftSettingUpsert {
	u.SetExcluded(bindkeygiftsetting.FieldConfig)
	return u
}

// ClearConfig clears the value of the "config" field.
func (u *BindKeyGiftSettingUpsert) ClearConfig() *BindKeyGiftSettingUpsert {
	u.SetNull(bindkeygiftsetting.FieldConfig)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BindKeyGiftSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BindKeyGiftSettingUpsertOne) UpdateNewValues() *BindKeyGiftSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(bindkeygiftsetting.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BindKeyGiftSetting.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BindKeyGiftSettingUpsertOne) Ignore() *BindKeyGiftSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BindKeyGiftSettingUpsertOne) DoNothing() *BindKeyGiftSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BindKeyGiftSettingCreate.OnConflict
// documentation for more info.
func (u *BindKeyGiftSettingUpsertOne) Update(set func(*BindKeyGiftSettingUpsert)) *BindKeyGiftSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BindKeyGiftSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BindKeyGiftSettingUpsertOne) SetUpdatedAt(v time.Time) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertOne) UpdateUpdatedAt() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *BindKeyGiftSettingUpsertOne) SetAPIKeyID(v int64) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *BindKeyGiftSettingUpsertOne) AddAPIKeyID(v int64) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertOne) UpdateAPIKeyID() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetDeductionMode sets the "deduction_mode" field.
func (u *BindKeyGiftSettingUpsertOne) SetDeductionMode(v string) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetDeductionMode(v)
	})
}

// UpdateDeductionMode sets the "deduction_mode" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertOne) UpdateDeductionMode() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateDeductionMode()
	})
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (u *BindKeyGiftSettingUpsertOne) SetRatioRecharge(v float64) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetRatioRecharge(v)
	})
}

// AddRatioRecharge adds v to the "ratio_recharge" field.
func (u *BindKeyGiftSettingUpsertOne) AddRatioRecharge(v float64) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.AddRatioRecharge(v)
	})
}

// UpdateRatioRecharge sets the "ratio_recharge" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertOne) UpdateRatioRecharge() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateRatioRecharge()
	})
}

// ClearRatioRecharge clears the value of the "ratio_recharge" field.
func (u *BindKeyGiftSettingUpsertOne) ClearRatioRecharge() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.ClearRatioRecharge()
	})
}

// SetExpiresAfterDays sets the "expires_after_days" field.
func (u *BindKeyGiftSettingUpsertOne) SetExpiresAfterDays(v int) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetExpiresAfterDays(v)
	})
}

// AddExpiresAfterDays adds v to the "expires_after_days" field.
func (u *BindKeyGiftSettingUpsertOne) AddExpiresAfterDays(v int) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.AddExpiresAfterDays(v)
	})
}

// UpdateExpiresAfterDays sets the "expires_after_days" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertOne) UpdateExpiresAfterDays() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateExpiresAfterDays()
	})
}

// ClearExpiresAfterDays clears the value of the "expires_after_days" field.
func (u *BindKeyGiftSettingUpsertOne) ClearExpiresAfterDays() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.ClearExpiresAfterDays()
	})
}

// SetActivityID sets the "activity_id" field.
func (u *BindKeyGiftSettingUpsertOne) SetActivityID(v int64) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetActivityID(v)
	})
}

// AddActivityID adds v to the "activity_id" field.
func (u *BindKeyGiftSettingUpsertOne) AddActivityID(v int64) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.AddActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertOne) UpdateActivityID() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateActivityID()
	})
}

// ClearActivityID clears the value of the "activity_id" field.
func (u *BindKeyGiftSettingUpsertOne) ClearActivityID() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.ClearActivityID()
	})
}

// SetConfig sets the "config" field.
func (u *BindKeyGiftSettingUpsertOne) SetConfig(v *domain.BindKeyConfig) *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertOne) UpdateConfig() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *BindKeyGiftSettingUpsertOne) ClearConfig() *BindKeyGiftSettingUpsertOne {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.ClearConfig()
	})
}

// Exec executes the query.
func (u *BindKeyGiftSettingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BindKeyGiftSettingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BindKeyGiftSettingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BindKeyGiftSettingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BindKeyGiftSettingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BindKeyGiftSettingCreateBulk is the builder for creating many BindKeyGiftSetting entities in bulk.
type BindKeyGiftSettingCreateBulk struct {
	config
	err      error
	builders []*BindKeyGiftSettingCreate
	conflict []sql.ConflictOption
}

// Save creates the BindKeyGiftSetting entities in the database.
func (_c *BindKeyGiftSettingCreateBulk) Save(ctx context.Context) ([]*BindKeyGiftSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BindKeyGiftSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BindKeyGiftSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BindKeyGiftSettingCreateBulk) SaveX(ctx context.Context) []*BindKeyGiftSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BindKeyGiftSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BindKeyGiftSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BindKeyGiftSetting.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BindKeyGiftSettingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BindKeyGiftSettingCreateBulk) OnConflict(opts ...sql.ConflictOption) *BindKeyGiftSettingUpsertBulk {
	_c.conflict = opts
	return &BindKeyGiftSettingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BindKeyGiftSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BindKeyGiftSettingCreateBulk) OnConflictColumns(columns ...string) *BindKeyGiftSettingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BindKeyGiftSettingUpsertBulk{
		create: _c,
	}
}

// BindKeyGiftSettingUpsertBulk is the builder for "upsert"-ing
// a bulk of BindKeyGiftSetting nodes.
type BindKeyGiftSettingUpsertBulk struct {
	create *BindKeyGiftSettingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BindKeyGiftSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BindKeyGiftSettingUpsertBulk) UpdateNewValues() *BindKeyGiftSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(bindkeygiftsetting.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BindKeyGiftSetting.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BindKeyGiftSettingUpsertBulk) Ignore() *BindKeyGiftSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BindKeyGiftSettingUpsertBulk) DoNothing() *BindKeyGiftSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BindKeyGiftSettingCreateBulk.OnConflict
// documentation for more info.
func (u *BindKeyGiftSettingUpsertBulk) Update(set func(*BindKeyGiftSettingUpsert)) *BindKeyGiftSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BindKeyGiftSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BindKeyGiftSettingUpsertBulk) SetUpdatedAt(v time.Time) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertBulk) UpdateUpdatedAt() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *BindKeyGiftSettingUpsertBulk) SetAPIKeyID(v int64) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *BindKeyGiftSettingUpsertBulk) AddAPIKeyID(v int64) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertBulk) UpdateAPIKeyID() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetDeductionMode sets the "deduction_mode" field.
func (u *BindKeyGiftSettingUpsertBulk) SetDeductionMode(v string) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetDeductionMode(v)
	})
}

// UpdateDeductionMode sets the "deduction_mode" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertBulk) UpdateDeductionMode() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateDeductionMode()
	})
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (u *BindKeyGiftSettingUpsertBulk) SetRatioRecharge(v float64) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetRatioRecharge(v)
	})
}

// AddRatioRecharge adds v to the "ratio_recharge" field.
func (u *BindKeyGiftSettingUpsertBulk) AddRatioRecharge(v float64) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.AddRatioRecharge(v)
	})
}

// UpdateRatioRecharge sets the "ratio_recharge" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertBulk) UpdateRatioRecharge() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateRatioRecharge()
	})
}

// ClearRatioRecharge clears the value of the "ratio_recharge" field.
func (u *BindKeyGiftSettingUpsertBulk) ClearRatioRecharge() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.ClearRatioRecharge()
	})
}

// SetExpiresAfterDays sets the "expires_after_days" field.
func (u *BindKeyGiftSettingUpsertBulk) SetExpiresAfterDays(v int) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetExpiresAfterDays(v)
	})
}

// AddExpiresAfterDays adds v to the "expires_after_days" field.
func (u *BindKeyGiftSettingUpsertBulk) AddExpiresAfterDays(v int) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.AddExpiresAfterDays(v)
	})
}

// UpdateExpiresAfterDays sets the "expires_after_days" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertBulk) UpdateExpiresAfterDays() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateExpiresAfterDays()
	})
}

// ClearExpiresAfterDays clears the value of the "expires_after_days" field.
func (u *BindKeyGiftSettingUpsertBulk) ClearExpiresAfterDays() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.ClearExpiresAfterDays()
	})
}

// SetActivityID sets the "activity_id" field.
func (u *BindKeyGiftSettingUpsertBulk) SetActivityID(v int64) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetActivityID(v)
	})
}

// AddActivityID adds v to the "activity_id" field.
func (u *BindKeyGiftSettingUpsertBulk) AddActivityID(v int64) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.AddActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertBulk) UpdateActivityID() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateActivityID()
	})
}

// ClearActivityID clears the value of the "activity_id" field.
func (u *BindKeyGiftSettingUpsertBulk) ClearActivityID() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.ClearActivityID()
	})
}

// SetConfig sets the "config" field.
func (u *BindKeyGiftSettingUpsertBulk) SetConfig(v *domain.BindKeyConfig) *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *BindKeyGiftSettingUpsertBulk) UpdateConfig() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *BindKeyGiftSettingUpsertBulk) ClearConfig() *BindKeyGiftSettingUpsertBulk {
	return u.Update(func(s *BindKeyGiftSettingUpsert) {
		s.ClearConfig()
	})
}

// Exec executes the query.
func (u *BindKeyGiftSettingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BindKeyGiftSettingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BindKeyGiftSettingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BindKeyGiftSettingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
