// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usergift"
)

// UserGiftCreate is the builder for creating a UserGift entity.
type UserGiftCreate struct {
	config
	mutation *UserGiftMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserGiftCreate) SetCreatedAt(v time.Time) *UserGiftCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserGiftCreate) SetNillableCreatedAt(v *time.Time) *UserGiftCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserGiftCreate) SetUpdatedAt(v time.Time) *UserGiftCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserGiftCreate) SetNillableUpdatedAt(v *time.Time) *UserGiftCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserGiftCreate) SetUserID(v int64) *UserGiftCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *UserGiftCreate) SetAmount(v float64) *UserGiftCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetRemaining sets the "remaining" field.
func (_c *UserGiftCreate) SetRemaining(v float64) *UserGiftCreate {
	_c.mutation.SetRemaining(v)
	return _c
}

// SetDeductionMode sets the "deduction_mode" field.
func (_c *UserGiftCreate) SetDeductionMode(v string) *UserGiftCreate {
	_c.mutation.SetDeductionMode(v)
	return _c
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (_c *UserGiftCreate) SetRatioRecharge(v float64) *UserGiftCreate {
	_c.mutation.SetRatioRecharge(v)
	return _c
}

// SetNillableRatioRecharge sets the "ratio_recharge" field if the given value is not nil.
func (_c *UserGiftCreate) SetNillableRatioRecharge(v *float64) *UserGiftCreate {
	if v != nil {
		_c.SetRatioRecharge(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserGiftCreate) SetExpiresAt(v time.Time) *UserGiftCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UserGiftCreate) SetNillableExpiresAt(v *time.Time) *UserGiftCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *UserGiftCreate) SetSource(v string) *UserGiftCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetSourceRef sets the "source_ref" field.
func (_c *UserGiftCreate) SetSourceRef(v string) *UserGiftCreate {
	_c.mutation.SetSourceRef(v)
	return _c
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_c *UserGiftCreate) SetNillableSourceRef(v *string) *UserGiftCreate {
	if v != nil {
		_c.SetSourceRef(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserGiftCreate) SetStatus(v string) *UserGiftCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserGiftCreate) SetNillableStatus(v *string) *UserGiftCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UserGiftCreate) SetGroupID(v int64) *UserGiftCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *UserGiftCreate) SetNillableGroupID(v *int64) *UserGiftCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetPinned sets the "pinned" field.
func (_c *UserGiftCreate) SetPinned(v bool) *UserGiftCreate {
	_c.mutation.SetPinned(v)
	return _c
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_c *UserGiftCreate) SetNillablePinned(v *bool) *UserGiftCreate {
	if v != nil {
		_c.SetPinned(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserGiftCreate) SetUser(v *User) *UserGiftCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserGiftMutation object of the builder.
func (_c *UserGiftCreate) Mutation() *UserGiftMutation {
	return _c.mutation
}

// Save creates the UserGift in the database.
func (_c *UserGiftCreate) Save(ctx context.Context) (*UserGift, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserGiftCreate) SaveX(ctx context.Context) *UserGift {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserGiftCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserGiftCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserGiftCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usergift.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usergift.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := usergift.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Pinned(); !ok {
		v := usergift.DefaultPinned
		_c.mutation.SetPinned(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserGiftCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserGift.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserGift.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserGift.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "UserGift.amount"`)}
	}
	if _, ok := _c.mutation.Remaining(); !ok {
		return &ValidationError{Name: "remaining", err: errors.New(`ent: missing required field "UserGift.remaining"`)}
	}
	if _, ok := _c.mutation.DeductionMode(); !ok {
		return &ValidationError{Name: "deduction_mode", err: errors.New(`ent: missing required field "UserGift.deduction_mode"`)}
	}
	if v, ok := _c.mutation.DeductionMode(); ok {
		if err := usergift.DeductionModeValidator(v); err != nil {
			return &ValidationError{Name: "deduction_mode", err: fmt.Errorf(`ent: validator failed for field "UserGift.deduction_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "UserGift.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := usergift.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "UserGift.source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceRef(); ok {
		if err := usergift.SourceRefValidator(v); err != nil {
			return &ValidationError{Name: "source_ref", err: fmt.Errorf(`ent: validator failed for field "UserGift.source_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserGift.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := usergift.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserGift.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pinned(); !ok {
		return &ValidationError{Name: "pinned", err: errors.New(`ent: missing required field "UserGift.pinned"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserGift.user"`)}
	}
	return nil
}

func (_c *UserGiftCreate) sqlSave(ctx context.Context) (*UserGift, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserGiftCreate) createSpec() (*UserGift, *sqlgraph.CreateSpec) {
	var (
		_node = &UserGift{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usergift.Table, sqlgraph.NewFieldSpec(usergift.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usergift.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usergift.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(usergift.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Remaining(); ok {
		_spec.SetField(usergift.FieldRemaining, field.TypeFloat64, value)
		_node.Remaining = value
	}
	if value, ok := _c.mutation.DeductionMode(); ok {
		_spec.SetField(usergift.FieldDeductionMode, field.TypeString, value)
		_node.DeductionMode = value
	}
	if value, ok := _c.mutation.RatioRecharge(); ok {
		_spec.SetField(usergift.FieldRatioRecharge, field.TypeFloat64, value)
		_node.RatioRecharge = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(usergift.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(usergift.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceRef(); ok {
		_spec.SetField(usergift.FieldSourceRef, field.TypeString, value)
		_node.SourceRef = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(usergift.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(usergift.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.Pinned(); ok {
		_spec.SetField(usergift.FieldPinned, field.TypeBool, value)
		_node.Pinned = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergift.UserTable,
			Columns: []string{usergift.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserGift.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserGiftUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserGiftCreate) OnConflict(opts ...sql.ConflictOption) *UserGiftUpsertOne {
	_c.conflict = opts
	return &UserGiftUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserGift.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserGiftCreate) OnConflictColumns(columns ...string) *UserGiftUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserGiftUpsertOne{
		create: _c,
	}
}

type (
	// UserGiftUpsertOne is the builder for "upsert"-ing
	//  one UserGift node.
	UserGiftUpsertOne struct {
		create *UserGiftCreate
	}

	// UserGiftUpsert is the "OnConflict" setter.
	UserGiftUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGiftUpsert) SetUpdatedAt(v time.Time) *UserGiftUpsert {
	u.Set(usergift.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateUpdatedAt() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserGiftUpsert) SetUserID(v int64) *UserGiftUpsert {
	u.Set(usergift.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateUserID() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldUserID)
	return u
}

// SetAmount sets the "amount" field.
func (u *UserGiftUpsert) SetAmount(v float64) *UserGiftUpsert {
	u.Set(usergift.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateAmount() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *UserGiftUpsert) AddAmount(v float64) *UserGiftUpsert {
	u.Add(usergift.FieldAmount, v)
	return u
}

// SetRemaining sets the "remaining" field.
func (u *UserGiftUpsert) SetRemaining(v float64) *UserGiftUpsert {
	u.Set(usergift.FieldRemaining, v)
	return u
}

// UpdateRemaining sets the "remaining" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateRemaining() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldRemaining)
	return u
}

// AddRemaining adds v to the "remaining" field.
func (u *UserGiftUpsert) AddRemaining(v float64) *UserGiftUpsert {
	u.Add(usergift.FieldRemaining, v)
	return u
}

// SetDeductionMode sets the "deduction_mode" field.
func (u *UserGiftUpsert) SetDeductionMode(v string) *UserGiftUpsert {
	u.Set(usergift.FieldDeductionMode, v)
	return u
}

// UpdateDeductionMode sets the "deduction_mode" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateDeductionMode() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldDeductionMode)
	return u
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (u *UserGiftUpsert) SetRatioRecharge(v float64) *UserGiftUpsert {
	u.Set(usergift.FieldRatioRecharge, v)
	return u
}

// UpdateRatioRecharge sets the "ratio_recharge" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateRatioRecharge() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldRatioRecharge)
	return u
}

// AddRatioRecharge adds v to the "ratio_recharge" field.
func (u *UserGiftUpsert) AddRatioRecharge(v float64) *UserGiftUpsert {
	u.Add(usergift.FieldRatioRecharge, v)
	return u
}

// ClearRatioRecharge clears the value of the "ratio_recharge" field.
func (u *UserGiftUpsert) ClearRatioRecharge() *UserGiftUpsert {
	u.SetNull(usergift.FieldRatioRecharge)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserGiftUpsert) SetExpiresAt(v time.Time) *UserGiftUpsert {
	u.Set(usergift.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateExpiresAt() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserGiftUpsert) ClearExpiresAt() *UserGiftUpsert {
	u.SetNull(usergift.FieldExpiresAt)
	return u
}

// SetSource sets the "source" field.
func (u *UserGiftUpsert) SetSource(v string) *UserGiftUpsert {
	u.Set(usergift.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateSource() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldSource)
	return u
}

// SetSourceRef sets the "source_ref" field.
func (u *UserGiftUpsert) SetSourceRef(v string) *UserGiftUpsert {
	u.Set(usergift.FieldSourceRef, v)
	return u
}

// UpdateSourceRef sets the "source_ref" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateSourceRef() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldSourceRef)
	return u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (u *UserGiftUpsert) ClearSourceRef() *UserGiftUpsert {
	u.SetNull(usergift.FieldSourceRef)
	return u
}

// SetStatus sets the "status" field.
func (u *UserGiftUpsert) SetStatus(v string) *UserGiftUpsert {
	u.Set(usergift.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateStatus() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldStatus)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UserGiftUpsert) SetGroupID(v int64) *UserGiftUpsert {
	u.Set(usergift.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdateGroupID() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGiftUpsert) AddGroupID(v int64) *UserGiftUpsert {
	u.Add(usergift.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UserGiftUpsert) ClearGroupID() *UserGiftUpsert {
	u.SetNull(usergift.FieldGroupID)
	return u
}

// SetPinned sets the "pinned" field.
func (u *UserGiftUpsert) SetPinned(v bool) *UserGiftUpsert {
	u.Set(usergift.FieldPinned, v)
	return u
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *UserGiftUpsert) UpdatePinned() *UserGiftUpsert {
	u.SetExcluded(usergift.FieldPinned)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserGift.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserGiftUpsertOne) UpdateNewValues() *UserGiftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usergift.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserGift.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserGiftUpsertOne) Ignore() *UserGiftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserGiftUpsertOne) DoNothing() *UserGiftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserGiftCreate.OnConflict
// documentation for more info.
func (u *UserGiftUpsertOne) Update(set func(*UserGiftUpsert)) *UserGiftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserGiftUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGiftUpsertOne) SetUpdatedAt(v time.Time) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateUpdatedAt() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserGiftUpsertOne) SetUserID(v int64) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateUserID() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *UserGiftUpsertOne) SetAmount(v float64) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserGiftUpsertOne) AddAmount(v float64) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateAmount() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateAmount()
	})
}

// SetRemaining sets the "remaining" field.
func (u *UserGiftUpsertOne) SetRemaining(v float64) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetRemaining(v)
	})
}

// AddRemaining adds v to the "remaining" field.
func (u *UserGiftUpsertOne) AddRemaining(v float64) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.AddRemaining(v)
	})
}

// UpdateRemaining sets the "remaining" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateRemaining() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateRemaining()
	})
}

// SetDeductionMode sets the "deduction_mode" field.
func (u *UserGiftUpsertOne) SetDeductionMode(v string) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetDeductionMode(v)
	})
}

// UpdateDeductionMode sets the "deduction_mode" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateDeductionMode() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateDeductionMode()
	})
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (u *UserGiftUpsertOne) SetRatioRecharge(v float64) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetRatioRecharge(v)
	})
}

// AddRatioRecharge adds v to the "ratio_recharge" field.
func (u *UserGiftUpsertOne) AddRatioRecharge(v float64) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.AddRatioRecharge(v)
	})
}

// UpdateRatioRecharge sets the "ratio_recharge" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateRatioRecharge() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateRatioRecharge()
	})
}

// ClearRatioRecharge clears the value of the "ratio_recharge" field.
func (u *UserGiftUpsertOne) ClearRatioRecharge() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.ClearRatioRecharge()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserGiftUpsertOne) SetExpiresAt(v time.Time) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateExpiresAt() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserGiftUpsertOne) ClearExpiresAt() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.ClearExpiresAt()
	})
}

// SetSource sets the "source" field.
func (u *UserGiftUpsertOne) SetSource(v string) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateSource() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateSource()
	})
}

// SetSourceRef sets the "source_ref" field.
func (u *UserGiftUpsertOne) SetSourceRef(v string) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetSourceRef(v)
	})
}

// UpdateSourceRef sets the "source_ref" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateSourceRef() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateSourceRef()
	})
}

// ClearSourceRef clears the value of the "source_ref" field.
func (u *UserGiftUpsertOne) ClearSourceRef() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.ClearSourceRef()
	})
}

// SetStatus sets the "status" field.
func (u *UserGiftUpsertOne) SetStatus(v string) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateStatus() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateStatus()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserGiftUpsertOne) SetGroupID(v int64) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGiftUpsertOne) AddGroupID(v int64) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdateGroupID() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UserGiftUpsertOne) ClearGroupID() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.ClearGroupID()
	})
}

// SetPinned sets the "pinned" field.
func (u *UserGiftUpsertOne) SetPinned(v bool) *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetPinned(v)
	})
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *UserGiftUpsertOne) UpdatePinned() *UserGiftUpsertOne {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdatePinned()
	})
}

// Exec executes the query.
func (u *UserGiftUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserGiftCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserGiftUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserGiftUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserGiftUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserGiftCreateBulk is the builder for creating many UserGift entities in bulk.
type UserGiftCreateBulk struct {
	config
	err      error
	builders []*UserGiftCreate
	conflict []sql.ConflictOption
}

// Save creates the UserGift entities in the database.
func (_c *UserGiftCreateBulk) Save(ctx context.Context) ([]*UserGift, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserGift, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserGiftMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserGiftCreateBulk) SaveX(ctx context.Context) []*UserGift {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserGiftCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserGiftCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserGift.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserGiftUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserGiftCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserGiftUpsertBulk {
	_c.conflict = opts
	return &UserGiftUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserGift.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserGiftCreateBulk) OnConflictColumns(columns ...string) *UserGiftUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserGiftUpsertBulk{
		create: _c,
	}
}

// UserGiftUpsertBulk is the builder for "upsert"-ing
// a bulk of UserGift nodes.
type UserGiftUpsertBulk struct {
	create *UserGiftCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserGift.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserGiftUpsertBulk) UpdateNewValues() *UserGiftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usergift.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserGift.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserGiftUpsertBulk) Ignore() *UserGiftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserGiftUpsertBulk) DoNothing() *UserGiftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserGiftCreateBulk.OnConflict
// documentation for more info.
func (u *UserGiftUpsertBulk) Update(set func(*UserGiftUpsert)) *UserGiftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserGiftUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGiftUpsertBulk) SetUpdatedAt(v time.Time) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateUpdatedAt() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserGiftUpsertBulk) SetUserID(v int64) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateUserID() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *UserGiftUpsertBulk) SetAmount(v float64) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserGiftUpsertBulk) AddAmount(v float64) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateAmount() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateAmount()
	})
}

// SetRemaining sets the "remaining" field.
func (u *UserGiftUpsertBulk) SetRemaining(v float64) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetRemaining(v)
	})
}

// AddRemaining adds v to the "remaining" field.
func (u *UserGiftUpsertBulk) AddRemaining(v float64) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.AddRemaining(v)
	})
}

// UpdateRemaining sets the "remaining" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateRemaining() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateRemaining()
	})
}

// SetDeductionMode sets the "deduction_mode" field.
func (u *UserGiftUpsertBulk) SetDeductionMode(v string) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetDeductionMode(v)
	})
}

// UpdateDeductionMode sets the "deduction_mode" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateDeductionMode() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateDeductionMode()
	})
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (u *UserGiftUpsertBulk) SetRatioRecharge(v float64) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetRatioRecharge(v)
	})
}

// AddRatioRecharge adds v to the "ratio_recharge" field.
func (u *UserGiftUpsertBulk) AddRatioRecharge(v float64) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.AddRatioRecharge(v)
	})
}

// UpdateRatioRecharge sets the "ratio_recharge" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateRatioRecharge() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateRatioRecharge()
	})
}

// ClearRatioRecharge clears the value of the "ratio_recharge" field.
func (u *UserGiftUpsertBulk) ClearRatioRecharge() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.ClearRatioRecharge()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserGiftUpsertBulk) SetExpiresAt(v time.Time) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateExpiresAt() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserGiftUpsertBulk) ClearExpiresAt() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.ClearExpiresAt()
	})
}

// SetSource sets the "source" field.
func (u *UserGiftUpsertBulk) SetSource(v string) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateSource() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateSource()
	})
}

// SetSourceRef sets the "source_ref" field.
func (u *UserGiftUpsertBulk) SetSourceRef(v string) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetSourceRef(v)
	})
}

// UpdateSourceRef sets the "source_ref" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateSourceRef() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateSourceRef()
	})
}

// ClearSourceRef clears the value of the "source_ref" field.
func (u *UserGiftUpsertBulk) ClearSourceRef() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.ClearSourceRef()
	})
}

// SetStatus sets the "status" field.
func (u *UserGiftUpsertBulk) SetStatus(v string) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateStatus() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateStatus()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserGiftUpsertBulk) SetGroupID(v int64) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGiftUpsertBulk) AddGroupID(v int64) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdateGroupID() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UserGiftUpsertBulk) ClearGroupID() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.ClearGroupID()
	})
}

// SetPinned sets the "pinned" field.
func (u *UserGiftUpsertBulk) SetPinned(v bool) *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.SetPinned(v)
	})
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *UserGiftUpsertBulk) UpdatePinned() *UserGiftUpsertBulk {
	return u.Update(func(s *UserGiftUpsert) {
		s.UpdatePinned()
	})
}

// Exec executes the query.
func (u *UserGiftUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserGiftCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserGiftCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserGiftUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
