// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usergift"
)

// UserGiftUpdate is the builder for updating UserGift entities.
type UserGiftUpdate struct {
	config
	hooks    []Hook
	mutation *UserGiftMutation
}

// Where appends a list predicates to the UserGiftUpdate builder.
func (_u *UserGiftUpdate) Where(ps ...predicate.UserGift) *UserGiftUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGiftUpdate) SetUpdatedAt(v time.Time) *UserGiftUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGiftUpdate) SetUserID(v int64) *UserGiftUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillableUserID(v *int64) *UserGiftUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserGiftUpdate) SetAmount(v float64) *UserGiftUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillableAmount(v *float64) *UserGiftUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserGiftUpdate) AddAmount(v float64) *UserGiftUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRemaining sets the "remaining" field.
func (_u *UserGiftUpdate) SetRemaining(v float64) *UserGiftUpdate {
	_u.mutation.ResetRemaining()
	_u.mutation.SetRemaining(v)
	return _u
}

// SetNillableRemaining sets the "remaining" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillableRemaining(v *float64) *UserGiftUpdate {
	if v != nil {
		_u.SetRemaining(*v)
	}
	return _u
}

// AddRemaining adds value to the "remaining" field.
func (_u *UserGiftUpdate) AddRemaining(v float64) *UserGiftUpdate {
	_u.mutation.AddRemaining(v)
	return _u
}

// SetDeductionMode sets the "deduction_mode" field.
func (_u *UserGiftUpdate) SetDeductionMode(v string) *UserGiftUpdate {
	_u.mutation.SetDeductionMode(v)
	return _u
}

// SetNillableDeductionMode sets the "deduction_mode" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillableDeductionMode(v *string) *UserGiftUpdate {
	if v != nil {
		_u.SetDeductionMode(*v)
	}
	return _u
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (_u *UserGiftUpdate) SetRatioRecharge(v float64) *UserGiftUpdate {
	_u.mutation.ResetRatioRecharge()
	_u.mutation.SetRatioRecharge(v)
	return _u
}

// SetNillableRatioRecharge sets the "ratio_recharge" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillableRatioRecharge(v *float64) *UserGiftUpdate {
	if v != nil {
		_u.SetRatioRecharge(*v)
	}
	return _u
}

// AddRatioRecharge adds value to the "ratio_recharge" field.
func (_u *UserGiftUpdate) AddRatioRecharge(v float64) *UserGiftUpdate {
	_u.mutation.AddRatioRecharge(v)
	return _u
}

// ClearRatioRecharge clears the value of the "ratio_recharge" field.
func (_u *UserGiftUpdate) ClearRatioRecharge() *UserGiftUpdate {
	_u.mutation.ClearRatioRecharge()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserGiftUpdate) SetExpiresAt(v time.Time) *UserGiftUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillableExpiresAt(v *time.Time) *UserGiftUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserGiftUpdate) ClearExpiresAt() *UserGiftUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetSource sets the "source" field.
func (_u *UserGiftUpdate) SetSource(v string) *UserGiftUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillableSource(v *string) *UserGiftUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *UserGiftUpdate) SetSourceRef(v string) *UserGiftUpdate {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillableSourceRef(v *string) *UserGiftUpdate {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (_u *UserGiftUpdate) ClearSourceRef() *UserGiftUpdate {
	_u.mutation.ClearSourceRef()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserGiftUpdate) SetStatus(v string) *UserGiftUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillableStatus(v *string) *UserGiftUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserGiftUpdate) SetGroupID(v int64) *UserGiftUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillableGroupID(v *int64) *UserGiftUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UserGiftUpdate) AddGroupID(v int64) *UserGiftUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *UserGiftUpdate) ClearGroupID() *UserGiftUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *UserGiftUpdate) SetPinned(v bool) *UserGiftUpdate {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *UserGiftUpdate) SetNillablePinned(v *bool) *UserGiftUpdate {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserGiftUpdate) SetUser(v *User) *UserGiftUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserGiftMutation object of the builder.
func (_u *UserGiftUpdate) Mutation() *UserGiftMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserGiftUpdate) ClearUser() *UserGiftUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserGiftUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGiftUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserGiftUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGiftUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGiftUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usergift.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGiftUpdate) check() error {
	if v, ok := _u.mutation.DeductionMode(); ok {
		if err := usergift.DeductionModeValidator(v); err != nil {
			return &ValidationError{Name: "deduction_mode", err: fmt.Errorf(`ent: validator failed for field "UserGift.deduction_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := usergift.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "UserGift.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceRef(); ok {
		if err := usergift.SourceRefValidator(v); err != nil {
			return &ValidationError{Name: "source_ref", err: fmt.Errorf(`ent: validator failed for field "UserGift.source_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usergift.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserGift.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGift.user"`)
	}
	return nil
}

func (_u *UserGiftUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergift.Table, usergift.Columns, sqlgraph.NewFieldSpec(usergift.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usergift.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(usergift.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(usergift.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Remaining(); ok {
		_spec.SetField(usergift.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemaining(); ok {
		_spec.AddField(usergift.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DeductionMode(); ok {
		_spec.SetField(usergift.FieldDeductionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RatioRecharge(); ok {
		_spec.SetField(usergift.FieldRatioRecharge, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRatioRecharge(); ok {
		_spec.AddField(usergift.FieldRatioRecharge, field.TypeFloat64, value)
	}
	if _u.mutation.RatioRechargeCleared() {
		_spec.ClearField(usergift.FieldRatioRecharge, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usergift.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(usergift.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(usergift.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(usergift.FieldSourceRef, field.TypeString, value)
	}
	if _u.mutation.SourceRefCleared() {
		_spec.ClearField(usergift.FieldSourceRef, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usergift.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(usergift.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(usergift.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(usergift.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(usergift.FieldPinned, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergift.UserTable,
			Columns: []string{usergift.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergift.UserTable,
			Columns: []string{usergift.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergift.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserGiftUpdateOne is the builder for updating a single UserGift entity.
type UserGiftUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGiftMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGiftUpdateOne) SetUpdatedAt(v time.Time) *UserGiftUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGiftUpdateOne) SetUserID(v int64) *UserGiftUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillableUserID(v *int64) *UserGiftUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserGiftUpdateOne) SetAmount(v float64) *UserGiftUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillableAmount(v *float64) *UserGiftUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserGiftUpdateOne) AddAmount(v float64) *UserGiftUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRemaining sets the "remaining" field.
func (_u *UserGiftUpdateOne) SetRemaining(v float64) *UserGiftUpdateOne {
	_u.mutation.ResetRemaining()
	_u.mutation.SetRemaining(v)
	return _u
}

// SetNillableRemaining sets the "remaining" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillableRemaining(v *float64) *UserGiftUpdateOne {
	if v != nil {
		_u.SetRemaining(*v)
	}
	return _u
}

// AddRemaining adds value to the "remaining" field.
func (_u *UserGiftUpdateOne) AddRemaining(v float64) *UserGiftUpdateOne {
	_u.mutation.AddRemaining(v)
	return _u
}

// SetDeductionMode sets the "deduction_mode" field.
func (_u *UserGiftUpdateOne) SetDeductionMode(v string) *UserGiftUpdateOne {
	_u.mutation.SetDeductionMode(v)
	return _u
}

// SetNillableDeductionMode sets the "deduction_mode" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillableDeductionMode(v *string) *UserGiftUpdateOne {
	if v != nil {
		_u.SetDeductionMode(*v)
	}
	return _u
}

// SetRatioRecharge sets the "ratio_recharge" field.
func (_u *UserGiftUpdateOne) SetRatioRecharge(v float64) *UserGiftUpdateOne {
	_u.mutation.ResetRatioRecharge()
	_u.mutation.SetRatioRecharge(v)
	return _u
}

// SetNillableRatioRecharge sets the "ratio_recharge" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillableRatioRecharge(v *float64) *UserGiftUpdateOne {
	if v != nil {
		_u.SetRatioRecharge(*v)
	}
	return _u
}

// AddRatioRecharge adds value to the "ratio_recharge" field.
func (_u *UserGiftUpdateOne) AddRatioRecharge(v float64) *UserGiftUpdateOne {
	_u.mutation.AddRatioRecharge(v)
	return _u
}

// ClearRatioRecharge clears the value of the "ratio_recharge" field.
func (_u *UserGiftUpdateOne) ClearRatioRecharge() *UserGiftUpdateOne {
	_u.mutation.ClearRatioRecharge()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserGiftUpdateOne) SetExpiresAt(v time.Time) *UserGiftUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillableExpiresAt(v *time.Time) *UserGiftUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserGiftUpdateOne) ClearExpiresAt() *UserGiftUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetSource sets the "source" field.
func (_u *UserGiftUpdateOne) SetSource(v string) *UserGiftUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillableSource(v *string) *UserGiftUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *UserGiftUpdateOne) SetSourceRef(v string) *UserGiftUpdateOne {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillableSourceRef(v *string) *UserGiftUpdateOne {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (_u *UserGiftUpdateOne) ClearSourceRef() *UserGiftUpdateOne {
	_u.mutation.ClearSourceRef()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserGiftUpdateOne) SetStatus(v string) *UserGiftUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillableStatus(v *string) *UserGiftUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserGiftUpdateOne) SetGroupID(v int64) *UserGiftUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillableGroupID(v *int64) *UserGiftUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UserGiftUpdateOne) AddGroupID(v int64) *UserGiftUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *UserGiftUpdateOne) ClearGroupID() *UserGiftUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *UserGiftUpdateOne) SetPinned(v bool) *UserGiftUpdateOne {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *UserGiftUpdateOne) SetNillablePinned(v *bool) *UserGiftUpdateOne {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserGiftUpdateOne) SetUser(v *User) *UserGiftUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserGiftMutation object of the builder.
func (_u *UserGiftUpdateOne) Mutation() *UserGiftMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserGiftUpdateOne) ClearUser() *UserGiftUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserGiftUpdate builder.
func (_u *UserGiftUpdateOne) Where(ps ...predicate.UserGift) *UserGiftUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserGiftUpdateOne) Select(field string, fields ...string) *UserGiftUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserGift entity.
func (_u *UserGiftUpdateOne) Save(ctx context.Context) (*UserGift, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGiftUpdateOne) SaveX(ctx context.Context) *UserGift {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserGiftUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGiftUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGiftUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usergift.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGiftUpdateOne) check() error {
	if v, ok := _u.mutation.DeductionMode(); ok {
		if err := usergift.DeductionModeValidator(v); err != nil {
			return &ValidationError{Name: "deduction_mode", err: fmt.Errorf(`ent: validator failed for field "UserGift.deduction_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := usergift.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "UserGift.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceRef(); ok {
		if err := usergift.SourceRefValidator(v); err != nil {
			return &ValidationError{Name: "source_ref", err: fmt.Errorf(`ent: validator failed for field "UserGift.source_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usergift.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserGift.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGift.user"`)
	}
	return nil
}

func (_u *UserGiftUpdateOne) sqlSave(ctx context.Context) (_node *UserGift, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergift.Table, usergift.Columns, sqlgraph.NewFieldSpec(usergift.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserGift.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergift.FieldID)
		for _, f := range fields {
			if !usergift.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usergift.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usergift.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(usergift.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(usergift.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Remaining(); ok {
		_spec.SetField(usergift.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemaining(); ok {
		_spec.AddField(usergift.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DeductionMode(); ok {
		_spec.SetField(usergift.FieldDeductionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RatioRecharge(); ok {
		_spec.SetField(usergift.FieldRatioRecharge, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRatioRecharge(); ok {
		_spec.AddField(usergift.FieldRatioRecharge, field.TypeFloat64, value)
	}
	if _u.mutation.RatioRechargeCleared() {
		_spec.ClearField(usergift.FieldRatioRecharge, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usergift.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(usergift.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(usergift.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(usergift.FieldSourceRef, field.TypeString, value)
	}
	if _u.mutation.SourceRefCleared() {
		_spec.ClearField(usergift.FieldSourceRef, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usergift.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(usergift.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(usergift.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(usergift.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(usergift.FieldPinned, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergift.UserTable,
			Columns: []string{usergift.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergift.UserTable,
			Columns: []string{usergift.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserGift{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergift.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
