// Code generated by ent, DO NOT EDIT.

package usergift

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usergift type in the database.
	Label = "user_gift"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldRemaining holds the string denoting the remaining field in the database.
	FieldRemaining = "remaining"
	// FieldDeductionMode holds the string denoting the deduction_mode field in the database.
	FieldDeductionMode = "deduction_mode"
	// FieldRatioRecharge holds the string denoting the ratio_recharge field in the database.
	FieldRatioRecharge = "ratio_recharge"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSourceRef holds the string denoting the source_ref field in the database.
	FieldSourceRef = "source_ref"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldPinned holds the string denoting the pinned field in the database.
	FieldPinned = "pinned"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the usergift in the database.
	Table = "user_gifts"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_gifts"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for usergift fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldAmount,
	FieldRemaining,
	FieldDeductionMode,
	FieldRatioRecharge,
	FieldExpiresAt,
	FieldSource,
	FieldSourceRef,
	FieldStatus,
	FieldGroupID,
	FieldPinned,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DeductionModeValidator is a validator for the "deduction_mode" field. It is called by the builders before save.
	DeductionModeValidator func(string) error
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// SourceRefValidator is a validator for the "source_ref" field. It is called by the builders before save.
	SourceRefValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultPinned holds the default value on creation for the "pinned" field.
	DefaultPinned bool
)

// OrderOption defines the ordering options for the UserGift queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByRemaining orders the results by the remaining field.
func ByRemaining(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemaining, opts...).ToFunc()
}

// ByDeductionMode orders the results by the deduction_mode field.
func ByDeductionMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeductionMode, opts...).ToFunc()
}

// ByRatioRecharge orders the results by the ratio_recharge field.
func ByRatioRecharge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRatioRecharge, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySourceRef orders the results by the source_ref field.
func BySourceRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceRef, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByPinned orders the results by the pinned field.
func ByPinned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPinned, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
