// Code generated by ent, DO NOT EDIT.

package usergift

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldAmount, v))
}

// Remaining applies equality check predicate on the "remaining" field. It's identical to RemainingEQ.
func Remaining(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldRemaining, v))
}

// DeductionMode applies equality check predicate on the "deduction_mode" field. It's identical to DeductionModeEQ.
func DeductionMode(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldDeductionMode, v))
}

// RatioRecharge applies equality check predicate on the "ratio_recharge" field. It's identical to RatioRechargeEQ.
func RatioRecharge(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldRatioRecharge, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldExpiresAt, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldSource, v))
}

// SourceRef applies equality check predicate on the "source_ref" field. It's identical to SourceRefEQ.
func SourceRef(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldSourceRef, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldStatus, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldGroupID, v))
}

// Pinned applies equality check predicate on the "pinned" field. It's identical to PinnedEQ.
func Pinned(v bool) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldPinned, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldAmount, v))
}

// RemainingEQ applies the EQ predicate on the "remaining" field.
func RemainingEQ(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldRemaining, v))
}

// RemainingNEQ applies the NEQ predicate on the "remaining" field.
func RemainingNEQ(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldRemaining, v))
}

// RemainingIn applies the In predicate on the "remaining" field.
func RemainingIn(vs ...float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldRemaining, vs...))
}

// RemainingNotIn applies the NotIn predicate on the "remaining" field.
func RemainingNotIn(vs ...float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldRemaining, vs...))
}

// RemainingGT applies the GT predicate on the "remaining" field.
func RemainingGT(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldRemaining, v))
}

// RemainingGTE applies the GTE predicate on the "remaining" field.
func RemainingGTE(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldRemaining, v))
}

// RemainingLT applies the LT predicate on the "remaining" field.
func RemainingLT(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldRemaining, v))
}

// RemainingLTE applies the LTE predicate on the "remaining" field.
func RemainingLTE(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldRemaining, v))
}

// DeductionModeEQ applies the EQ predicate on the "deduction_mode" field.
func DeductionModeEQ(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldDeductionMode, v))
}

// DeductionModeNEQ applies the NEQ predicate on the "deduction_mode" field.
func DeductionModeNEQ(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldDeductionMode, v))
}

// DeductionModeIn applies the In predicate on the "deduction_mode" field.
func DeductionModeIn(vs ...string) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldDeductionMode, vs...))
}

// DeductionModeNotIn applies the NotIn predicate on the "deduction_mode" field.
func DeductionModeNotIn(vs ...string) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldDeductionMode, vs...))
}

// DeductionModeGT applies the GT predicate on the "deduction_mode" field.
func DeductionModeGT(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldDeductionMode, v))
}

// DeductionModeGTE applies the GTE predicate on the "deduction_mode" field.
func DeductionModeGTE(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldDeductionMode, v))
}

// DeductionModeLT applies the LT predicate on the "deduction_mode" field.
func DeductionModeLT(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldDeductionMode, v))
}

// DeductionModeLTE applies the LTE predicate on the "deduction_mode" field.
func DeductionModeLTE(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldDeductionMode, v))
}

// DeductionModeContains applies the Contains predicate on the "deduction_mode" field.
func DeductionModeContains(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldContains(FieldDeductionMode, v))
}

// DeductionModeHasPrefix applies the HasPrefix predicate on the "deduction_mode" field.
func DeductionModeHasPrefix(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldHasPrefix(FieldDeductionMode, v))
}

// DeductionModeHasSuffix applies the HasSuffix predicate on the "deduction_mode" field.
func DeductionModeHasSuffix(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldHasSuffix(FieldDeductionMode, v))
}

// DeductionModeEqualFold applies the EqualFold predicate on the "deduction_mode" field.
func DeductionModeEqualFold(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEqualFold(FieldDeductionMode, v))
}

// DeductionModeContainsFold applies the ContainsFold predicate on the "deduction_mode" field.
func DeductionModeContainsFold(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldContainsFold(FieldDeductionMode, v))
}

// RatioRechargeEQ applies the EQ predicate on the "ratio_recharge" field.
func RatioRechargeEQ(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldRatioRecharge, v))
}

// RatioRechargeNEQ applies the NEQ predicate on the "ratio_recharge" field.
func RatioRechargeNEQ(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldRatioRecharge, v))
}

// RatioRechargeIn applies the In predicate on the "ratio_recharge" field.
func RatioRechargeIn(vs ...float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldRatioRecharge, vs...))
}

// RatioRechargeNotIn applies the NotIn predicate on the "ratio_recharge" field.
func RatioRechargeNotIn(vs ...float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldRatioRecharge, vs...))
}

// RatioRechargeGT applies the GT predicate on the "ratio_recharge" field.
func RatioRechargeGT(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldRatioRecharge, v))
}

// RatioRechargeGTE applies the GTE predicate on the "ratio_recharge" field.
func RatioRechargeGTE(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldRatioRecharge, v))
}

// RatioRechargeLT applies the LT predicate on the "ratio_recharge" field.
func RatioRechargeLT(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldRatioRecharge, v))
}

// RatioRechargeLTE applies the LTE predicate on the "ratio_recharge" field.
func RatioRechargeLTE(v float64) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldRatioRecharge, v))
}

// RatioRechargeIsNil applies the IsNil predicate on the "ratio_recharge" field.
func RatioRechargeIsNil() predicate.UserGift {
	return predicate.UserGift(sql.FieldIsNull(FieldRatioRecharge))
}

// RatioRechargeNotNil applies the NotNil predicate on the "ratio_recharge" field.
func RatioRechargeNotNil() predicate.UserGift {
	return predicate.UserGift(sql.FieldNotNull(FieldRatioRecharge))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.UserGift {
	return predicate.UserGift(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.UserGift {
	return predicate.UserGift(sql.FieldNotNull(FieldExpiresAt))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldContainsFold(FieldSource, v))
}

// SourceRefEQ applies the EQ predicate on the "source_ref" field.
func SourceRefEQ(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldSourceRef, v))
}

// SourceRefNEQ applies the NEQ predicate on the "source_ref" field.
func SourceRefNEQ(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldSourceRef, v))
}

// SourceRefIn applies the In predicate on the "source_ref" field.
func SourceRefIn(vs ...string) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldSourceRef, vs...))
}

// SourceRefNotIn applies the NotIn predicate on the "source_ref" field.
func SourceRefNotIn(vs ...string) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldSourceRef, vs...))
}

// SourceRefGT applies the GT predicate on the "source_ref" field.
func SourceRefGT(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldSourceRef, v))
}

// SourceRefGTE applies the GTE predicate on the "source_ref" field.
func SourceRefGTE(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldSourceRef, v))
}

// SourceRefLT applies the LT predicate on the "source_ref" field.
func SourceRefLT(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldSourceRef, v))
}

// SourceRefLTE applies the LTE predicate on the "source_ref" field.
func SourceRefLTE(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldSourceRef, v))
}

// SourceRefContains applies the Contains predicate on the "source_ref" field.
func SourceRefContains(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldContains(FieldSourceRef, v))
}

// SourceRefHasPrefix applies the HasPrefix predicate on the "source_ref" field.
func SourceRefHasPrefix(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldHasPrefix(FieldSourceRef, v))
}

// SourceRefHasSuffix applies the HasSuffix predicate on the "source_ref" field.
func SourceRefHasSuffix(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldHasSuffix(FieldSourceRef, v))
}

// SourceRefIsNil applies the IsNil predicate on the "source_ref" field.
func SourceRefIsNil() predicate.UserGift {
	return predicate.UserGift(sql.FieldIsNull(FieldSourceRef))
}

// SourceRefNotNil applies the NotNil predicate on the "source_ref" field.
func SourceRefNotNil() predicate.UserGift {
	return predicate.UserGift(sql.FieldNotNull(FieldSourceRef))
}

// SourceRefEqualFold applies the EqualFold predicate on the "source_ref" field.
func SourceRefEqualFold(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEqualFold(FieldSourceRef, v))
}

// SourceRefContainsFold applies the ContainsFold predicate on the "source_ref" field.
func SourceRefContainsFold(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldContainsFold(FieldSourceRef, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserGift {
	return predicate.UserGift(sql.FieldContainsFold(FieldStatus, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.UserGift {
	return predicate.UserGift(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.UserGift {
	return predicate.UserGift(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.UserGift {
	return predicate.UserGift(sql.FieldNotNull(FieldGroupID))
}

// PinnedEQ applies the EQ predicate on the "pinned" field.
func PinnedEQ(v bool) predicate.UserGift {
	return predicate.UserGift(sql.FieldEQ(FieldPinned, v))
}

// PinnedNEQ applies the NEQ predicate on the "pinned" field.
func PinnedNEQ(v bool) predicate.UserGift {
	return predicate.UserGift(sql.FieldNEQ(FieldPinned, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserGift {
	return predicate.UserGift(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserGift {
	return predicate.UserGift(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserGift) predicate.UserGift {
	return predicate.UserGift(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserGift) predicate.UserGift {
	return predicate.UserGift(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserGift) predicate.UserGift {
	return predicate.UserGift(sql.NotPredicates(p))
}
